import Head from "next/head";
import BigSightNavbar from "../../containers/Navbar/BigSightNavbar";
import "bootstrap/dist/css/bootstrap.min.css";

const Index = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={"Navbar-Container"}>
                <BigSightNavbar />
            </div>
            <div className={"Content-Container"}></div>
        </div>
    );
};

export default Index;
