import Head from "next/head";
import React from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import BigSightNavbar from "../../containers/Navbar/BigSightNavbar";
import FaqSection1 from "../../containers/Faq/Faq-Section1/Faq-Section1";
import BeforeFooter from "../../containers/Footer/BeforeFooterBighSight";
import FooterBigSight from "../../containers/Footer/Footer";

export default function faq() {
    return (
        <div>
            <Head>
                <title>FAQ Big Sight</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>{" "}
            <div className={"Navbar-Container"}>
                <BigSightNavbar />
            </div>
            <div className={"Content-Container"}>
                <FaqSection1 />
                <BeforeFooter />
                <FooterBigSight />
            </div>
        </div>
    );
}
